[project]
name = "python-money"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django==4.0.10",
]

[dependency-groups]
test = [
    "mypy>=1.11.0",
    "ruff>=0.8.3",
]